import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import { ThemeProvider } from "./context/ThemeContext";

export const metadata = {
  title: "Code Snippet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <Analytics />
      <body suppressHydrationWarning className="bg-zinc-900">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
